### PR TITLE
fixing according to doc

### PR DESCRIPTION
**Pull request by BlueHotDog**
https://date-fns.org/v2.16.1/docs/fp/setDay

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Are you looking for a new method? Just add it. 

I see both options available: 
image

**Comment by BlueHotDog** [comment]
they both are the same.. look at the actual export

**Review by dmtrKovalenko — APPROVED** [review]
See it! Thank you @BlueHotDog  :)

**Comment by BlueHotDog** [comment]
np :) happy to help. fyi i got an alert about this even without using it through CRA. i guess it does some basic checks to make sure types are actually exported. would be cool to run this as a test suite.

**Pull request merged**
